# Generated by Django 5.2 on 2025-05-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                ("name", models.CharField(max_length=50)),
                ("company_id", models.AutoField(primary_key=True, serialize=False)),
                ("location", models.CharField(max_length=100)),
                ("about", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("IT", "IT"),
                            ("NON-IT", "NON-IT"),
                            ("Mobile Phone", "Mobile Phone"),
                        ],
                        max_length=100,
                    ),
                ),
                ("phone_number", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("added_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
